services:
  postgres:
    image: postgres:15-alpine
    container_name: omv-jd-dashboard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nexus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nexus}
      POSTGRES_DB: ${POSTGRES_DB:-nexus_db}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: omv-jd-dashboard-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    image: ghcr.io/nchungdev/omv-jdownloader-dashboard-api:latest
    container_name: omv-jd-dashboard-api
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    ports:
      - "8086:8086"
    environment:
      - MYJD_EMAIL=${MYJD_EMAIL}
      - MYJD_PASSWORD=${MYJD_PASSWORD}
      - TMDB_READ_ACCESS_TOKEN=${TMDB_READ_ACCESS_TOKEN}
      - STORAGE_PATH=/storage
      - JD_DOWNLOAD_BASE=/storage
      - JD_INTERNAL_PATH=/downloads
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://${POSTGRES_USER:-nexus}:${POSTGRES_PASSWORD:-nexus}@postgres:5432/${POSTGRES_DB:-nexus_db}
    volumes:
      - ${HOST_STORAGE_PATH}:/storage

  frontend:
    image: ghcr.io/nchungdev/omv-jdownloader-dashboard-ui:latest
    container_name: omv-jd-dashboard-ui
    restart: unless-stopped
    ports:
      - "8087:80"
